root: true

parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: "module"

  extends:
  - airbnb-base
  - import-warnings

env:
  browser: true
  node: true
  es6: true
  mocha: true

ignorePatterns: ['dist/**']

rules:
  # semis begone
  semi: [2, 'never']